version: "3.8"

networks:
  node-api-network:
    name: node-api-network

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql_server
    networks:
      - node-api-network

  mysql_server:
    image: mysql
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=testing
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - node-api-network
